# Generated by Django 4.1.4 on 2023-02-02 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
